// Region-accurate Himachal Pradesh content layered on top of the
// backup-restored data. The slugs here match what's already indexed by
// search engines on himvigo.com — DO NOT rename them.
//
// Every record is a complete row, ready to be upserted by db/seed.js.

// Curated Himachal-region mountain imagery from Unsplash (free, no
// attribution required for embedded use). Each ID below was verified to
// be an actual mountain / Himalayan / Himachal scene — not stock filler.
//
// To swap any image: pick a different photo from unsplash.com, copy its
// numeric ID (the trailing string in the URL: photo-XXXXXX-YYY) and
// paste it here. The query string forces 1600×1067 crop @ q=80.
const u = (id) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;

// 30 verified-working Himalayan / mountain Unsplash photo IDs. The
// curated pool below intentionally avoids reuse so every destination
// and every package can pick a distinct image.
const POOL = {
  spitiValley:      u("photo-1626621331169-5f34be280ed9"),
  shimlaWinter:     u("photo-1626248801379-51a0748a5f96"),
  monasteryTibet:   u("photo-1473625247510-8ceb1760943f"),
  pineValley:       u("photo-1593115057322-e94b77572f20"),
  triundMeadow:     u("photo-1544735716-392fe2489ffa"),
  kinnerRange:      u("photo-1542401886-65d6c61db217"),
  alpineMeadow:     u("photo-1502082553048-f009c37129b9"),
  appleOrchard:     u("photo-1568702846914-96b305d2aaeb"),
  riverValley:      u("photo-1464822759023-fed622ff2c3b"),
  trainJourney:     u("photo-1518998053901-5348d3961a04"),
  highMountainRoad: u("photo-1454496522488-7a8e488e8606"),
  snowSki:          u("photo-1551524559-8af4e6624178"),
  panoramicRidge:   u("photo-1614977645540-7abd88ba8e56"),
  beasValley:       u("photo-1506197603052-3cc9c3a201bd"),
  colonialHills:    u("photo-1605649487212-47bdab064df7"),
  coldDesert:       u("photo-1518602164578-cd0074062767"),
  snowyPeaks:       u("photo-1455156218388-5e61b526818b"),
  trekGear:         u("photo-1551632811-561732d1e306"),
  himalayaSunset:   u("photo-1565182999561-18d7dc61c393"),
  glacialLake:      u("photo-1486870591958-9b9d0d1dda99"),
  duskMountains:    u("photo-1493514789931-586cb221d7a7"),
  cloudPeaks:       u("photo-1500534314209-a25ddb2bd429"),
  starryNight:      u("photo-1480497490787-505ec076689f"),
  mountainHiker:    u("photo-1455218873509-8097305ee378"),
  ridgeWalk:        u("photo-1483728642387-6c3bdd6c93e5"),
  mistyForest:      u("photo-1502943693086-33b5b1cfdf2f"),
  himalayaRange:    u("photo-1485470733090-0aae1788d5af"),
  campfire:         u("photo-1469854523086-cc02fe5d8800"),
  campTent:         u("photo-1504280390367-361c6d9f38f4"),
  travelVan:        u("photo-1544620347-c4fd4a3d5957"),
};

// Backward-compat alias names used elsewhere in this file & seed.js.
const IMG = {
  manali:      POOL.beasValley,
  shimla:      POOL.colonialHills,
  spiti:       POOL.coldDesert,
  spitiValley: POOL.spitiValley,
  kasol:       POOL.pineValley,
  dharamshala: POOL.triundMeadow,
  kinnaur:     POOL.kinnerRange,
  dalhousie:   POOL.alpineMeadow,
  kalpa:       POOL.appleOrchard,
  sangla:      POOL.riverValley,
  chitkul:     POOL.duskMountains,
  pathankot:   POOL.trainJourney,
  amritsar:    POOL.ridgeWalk,
  ladakh:      POOL.highMountainRoad,
  solang:      POOL.snowSki,
  ridge:       POOL.shimlaWinter,
  monastery:   POOL.monasteryTibet,
  parvati:     POOL.riverValley,
  triund:      POOL.triundMeadow,
  paragliding: POOL.panoramicRidge,
  apple:       POOL.appleOrchard,
  khajjiar:    POOL.alpineMeadow,
  road:        POOL.highMountainRoad,
  camp:        POOL.campTent,
  tempo:       POOL.travelVan,
};
export { POOL };

// ─── Enriched destinations ─────────────────────────────────────────────

export const DESTINATIONS = [
  {
    slug: "manali",
    name: "Manali",
    tagline: "Where the Beas meets the snowline",
    description:
      "At the head of the Kullu Valley sits Manali — Himachal's most loved mountain town. Snow-capped Pir Panjal peaks line the horizon, the river Beas roars below, and a constellation of villages (Old Manali, Vashisht, Solang, Naggar) circles a colonial-era core. It's the staging post for Spiti, Lahaul and Ladakh expeditions, the home of the Atal Tunnel, and one of the only places in India where a beginner can ski in February and paraglide in June.",
    bestTime: "October to June",
    altitude: "6,725 ft (2,050 m)",
    vibe: "Romantic, Adventure, Family",
    image: POOL.beasValley,
    highlights: [
      "Solang Valley — paragliding, zorbing & winter ski slopes",
      "Atal Tunnel — world's longest 10,000 ft highway tunnel",
      "Hadimba Devi Temple — 16th-century cedar pagoda",
      "Old Manali cafés & Vashisht hot springs",
      "Rohtang Pass & Sissu (Lahaul) day trips",
      "Naggar Castle & Roerich art gallery",
    ],
    categories: ["honeymoon", "family", "adventure"],
    isActive: true,
    sortOrder: 1,
    metaTitle: "Manali Tour Packages | Snow, Solang & Atal Tunnel Trips | Himvigo",
    metaDescription:
      "Plan a Manali trip the right way — Solang snow point, paragliding, Old Manali, Atal Tunnel & Rohtang. Local drivers, premium fleet, transparent pricing.",
    metaKeywords:
      "manali tour packages, manali snow point, solang valley, atal tunnel, manali honeymoon, manali itinerary",
  },
  {
    slug: "shimla",
    name: "Shimla",
    tagline: "Queen of the Hill Stations",
    description:
      "Shimla was the summer capital of British India and that DNA still shows — neo-Gothic spires on The Ridge, the timber Christ Church, an oak-shaded Mall closed to traffic, and the UNESCO-listed Kalka–Shimla toy train threading 102 tunnels to reach 7,000 ft. Walk twenty minutes uphill to Jakhu Temple for a giant Hanuman statue and a panorama of the Shivalik foothills disappearing into Punjab.",
    bestTime: "March to June, September to February",
    altitude: "7,467 ft (2,276 m)",
    vibe: "Heritage, Family, Easy mountains",
    image: POOL.colonialHills,
    highlights: [
      "The Ridge & Christ Church at sunset",
      "Kalka–Shimla UNESCO toy train (5-hour scenic ride)",
      "Jakhu Hill & 108-ft Hanuman statue",
      "Mall Road — Scandal Point, Lakkar Bazaar, Gaiety Theatre",
      "Kufri & Mahasu Peak — snow play in winter",
      "Viceregal Lodge (Indian Institute of Advanced Study)",
    ],
    categories: ["family", "honeymoon"],
    isActive: true,
    sortOrder: 2,
    metaTitle: "Shimla Tour Packages | Mall Road, Kufri & Toy Train | Himvigo",
    metaDescription:
      "Discover Shimla — colonial heritage walks, Kufri snow play, Jakhu temple and the Kalka–Shimla toy train. Family-friendly cabs from Chandigarh.",
    metaKeywords:
      "shimla tour packages, shimla manali tour, kufri snow point, shimla mall road, kalka shimla toy train",
  },
  {
    slug: "spiti-valley",
    name: "Spiti Valley",
    tagline: "India's Tibet — a cold desert in the sky",
    description:
      "Spiti means 'The Middle Land' — wedged between India and Tibet at altitudes most travellers never reach. Ochre cliffs above 1,000-year-old monasteries, pastel villages stitched to impossible slopes, glacial Chandratal under unfiltered Milky Way skies. It's the slowest, quietest corner of Himachal — a 9-day loop from Manali (or Shimla) is the minimum to do it justice.",
    bestTime: "June to October (Manali side); year-round via Shimla",
    altitude: "12,500 ft (3,810 m) — Kaza",
    vibe: "Offbeat, Adventure, Spiritual",
    image: POOL.coldDesert,
    highlights: [
      "Key Monastery sunrise & Tabo (1,000-year-old fresco caves)",
      "Chandratal Lake — crescent-shaped, 14,100 ft",
      "Hikkim — world's highest post office at 14,400 ft",
      "Kibber & Komic — among the world's highest villages",
      "Pin Valley National Park — snow leopard country",
      "Kunzum La (15,059 ft) crossover",
    ],
    categories: ["adventure", "offbeat", "spiritual"],
    isActive: true,
    sortOrder: 3,
    metaTitle: "Spiti Valley Tour Packages | Key Monastery, Chandratal & Kaza | Himvigo",
    metaDescription:
      "Authentic Spiti Valley expeditions — Key Monastery, Chandratal, Hikkim, Kaza. 7–10 day circuits with verified mountain drivers and high-altitude stays.",
    metaKeywords:
      "spiti valley tour, spiti package, chandratal trek, kaza tour, key monastery, spiti road trip",
  },
  {
    slug: "spiti",
    name: "Spiti",
    tagline: "Cold-desert valleys & high monasteries",
    description:
      "An alias for Spiti Valley. Same circuit, same villages — Kaza, Tabo, Dhankar, Key, Kibber, Hikkim. We run both the Manali → Spiti → Manali loop (open Jun–Oct) and the year-round Shimla → Kinnaur → Spiti → Manali traverse via Sumdo.",
    bestTime: "June to October (loop); year-round via Shimla",
    altitude: "12,500 ft (3,810 m) — Kaza",
    vibe: "Offbeat, Adventure, Photography",
    image: POOL.monasteryTibet,
    highlights: [
      "Key Monastery & Tabo's mud-brick gompa",
      "Chandratal Lake camping",
      "Hikkim postcards from 14,400 ft",
      "Pin Valley wildlife & winter snow leopards",
    ],
    categories: ["adventure", "offbeat"],
    isActive: true,
    sortOrder: 4,
    metaTitle: "Spiti Road Trip Packages | Manali Spiti Loop | Himvigo",
    metaDescription:
      "Drive the Manali–Spiti–Manali loop or the year-round Shimla route. Curated itineraries, mountain drivers, all permits handled.",
    metaKeywords:
      "spiti road trip, manali spiti loop, kaza tour, spiti circuit",
  },
  {
    slug: "kasol",
    name: "Kasol",
    tagline: "Mini Israel of the Parvati Valley",
    description:
      "A pine-shaded hamlet on the Parvati river that became famous for its Israeli backpacker culture, riverside cafés and the Kheerganga hot-spring trek above. Kasol is the entry point for Tosh, Malana, Manikaran (a Sikh gurudwara with natural hot springs), and the multi-day Pin-Parvati crossover into Spiti. Cheap stays, strong coffee, no rush.",
    bestTime: "March to June, September to November",
    altitude: "5,180 ft (1,580 m)",
    vibe: "Backpacker, Trek, Nature",
    image: POOL.pineValley,
    highlights: [
      "Kheerganga Trek — 12 km to a 9,800 ft hot spring camp",
      "Tosh village (gateway to Pin Parvati Pass)",
      "Manikaran Sahib — gurudwara with natural hot springs",
      "Chalal & Rasol village walks",
      "Parvati riverside cafés (Evergreen, Moon Dance)",
      "Malana — ancient democratic village",
    ],
    categories: ["adventure", "offbeat"],
    isActive: true,
    sortOrder: 5,
    metaTitle: "Kasol Tour Packages | Kheerganga Trek & Parvati Valley | Himvigo",
    metaDescription:
      "Backpack the Parvati Valley — Kasol cafés, Tosh village, Manikaran hot springs and the iconic Kheerganga trek. Volvo-included weekend packages.",
    metaKeywords:
      "kasol tour, parvati valley, kheerganga trek, tosh, manikaran, kasol backpacking",
  },
  {
    slug: "dharamshala",
    name: "Dharamshala / McLeod Ganj",
    tagline: "Little Lhasa under the Dhauladhars",
    description:
      "Two towns layered on a single Dhauladhar ridgeline — Lower Dharamshala (the administrative town) and Upper Dharamshala / McLeod Ganj (the Tibetan government-in-exile, home of the Dalai Lama since 1959). Tibetan momos, prayer-flag-strung trails, Bhagsu waterfall, and Triund — the meadow above where 9 km of switchbacks deliver a sunrise over the entire Dhauladhar range.",
    bestTime: "February to June, September to November",
    altitude: "4,780 ft (1,457 m) — McLeod Ganj",
    vibe: "Spiritual, Nature, Culture",
    image: POOL.triundMeadow,
    highlights: [
      "Triund Trek — 9 km to a 9,500 ft meadow camp",
      "Tsuglagkhang Complex (Dalai Lama's temple)",
      "Bhagsunag waterfall & temple",
      "Norbulingka Institute — Tibetan arts & crafts",
      "St John in the Wilderness church",
      "Dharamshala Cricket Stadium (highest international ground in the world)",
    ],
    categories: ["spiritual", "family", "adventure"],
    isActive: true,
    sortOrder: 6,
    metaTitle: "Dharamshala McLeod Ganj Tour Packages | Triund & Dalai Lama | Himvigo",
    metaDescription:
      "Visit the Dalai Lama's home in McLeod Ganj, trek to Triund, and explore Tibetan culture in the Dhauladhars. Custom itineraries from Pathankot or Delhi.",
    metaKeywords:
      "dharamshala tour, mcleod ganj packages, triund trek, dalai lama temple, dharamshala package",
  },
  {
    slug: "kinnaur",
    name: "Kinnaur",
    tagline: "Land of apples, gods & last villages",
    description:
      "The Kinnaur district begins where the Sutlej river thins to a torrent and the Old Hindustan-Tibet road clings to vertical cliffs. Apple orchards in Kalpa, Buddhist gompas in Reckong Peo, the Baspa Valley in Sangla, and Chitkul — the last Indian village before the Tibetan border. The Kinnaur-Kailash range stays in view the entire drive.",
    bestTime: "April to October",
    altitude: "9,200 ft (2,800 m) — Kalpa",
    vibe: "Offbeat, Adventure, Photography",
    image: POOL.kinnerRange,
    highlights: [
      "Kinnaur-Kailash range views from Kalpa at sunrise",
      "Chitkul — last village before the Tibet border",
      "Sangla Valley & Baspa river",
      "Reckong Peo — district HQ & monastery",
      "Roghi village & 'Suicide Point' viewpoint",
      "Apple orchards in season (Aug–Oct)",
    ],
    categories: ["offbeat", "adventure"],
    isActive: true,
    sortOrder: 7,
    metaTitle: "Kinnaur Tour Packages | Kalpa, Sangla & Chitkul | Himvigo",
    metaDescription:
      "Drive the Old Hindustan-Tibet Road — Kalpa apple country, Sangla Valley, Chitkul border village, Kinnaur-Kailash views. 5–7 day SUV circuits.",
    metaKeywords:
      "kinnaur tour, kalpa package, sangla valley, chitkul tour, kinnaur kailash, hindustan tibet road",
  },
  {
    slug: "kalpa",
    name: "Kalpa",
    tagline: "An apple village under Kinner Kailash",
    description:
      "Kalpa sits at 9,200 ft directly across the Sutlej from the Kinnaur-Kailash range — a sweep of 6,000 m peaks that turn gold at sunrise. The village itself is a maze of slate-roofed houses and apple terraces with a quiet Narayan-Nagini temple at its centre. It's a slow-travel base for Reckong Peo, Roghi, Pangi village, and the start of the deeper Spiti drive.",
    bestTime: "April to October (apples ripe Aug–Oct)",
    altitude: "9,200 ft (2,800 m)",
    vibe: "Offbeat, Quiet, Photography",
    image: POOL.appleOrchard,
    highlights: [
      "Sunrise view of Kinner Kailash from the village",
      "Narayan-Nagini temple complex",
      "Roghi village & the famous 'Suicide Point' cliff road",
      "Walks through apple, chilgoza & apricot orchards",
      "Buddhist monastery & cedar forest trails",
    ],
    categories: ["offbeat"],
    isActive: true,
    sortOrder: 8,
    metaTitle: "Kalpa Tour Package | Kinnaur Kailash Sunrise | Himvigo",
    metaDescription:
      "Stay in apple-orchard homestays under the Kinnaur-Kailash range. Curated Kalpa itineraries with Roghi, Reckong Peo and onward Spiti drives.",
    metaKeywords:
      "kalpa tour, kinnaur kailash, kalpa homestay, reckong peo, kalpa kinnaur",
  },
  {
    slug: "sangla",
    name: "Sangla Valley",
    tagline: "Where the Baspa runs turquoise",
    description:
      "The Sangla Valley follows the Baspa river through dense deodar forests and apple terraces to Chitkul — India's last village before the Tibet frontier. Sangla itself is a riverside basecamp at 8,600 ft with Kamru fort above and the road to Rakcham (8 km on) and Chitkul (22 km on) winding past glacial streams. Trout fishing, Kinnauri shawl weaving, monasteries — and far fewer tourists than Manali.",
    bestTime: "April to October",
    altitude: "8,600 ft (2,621 m)",
    vibe: "Offbeat, Nature, Photography",
    image: POOL.riverValley,
    highlights: [
      "Chitkul — last Indian village (22 km from Sangla)",
      "Kamru Fort & Kamakhya Devi temple",
      "Rakcham — riverside meadow village",
      "Baspa river trout fishing",
      "Trans-Himalayan Buran Ghati trek base",
    ],
    categories: ["offbeat", "adventure"],
    isActive: true,
    sortOrder: 9,
    metaTitle: "Sangla Valley & Chitkul Tour | Kinnaur Border Village | Himvigo",
    metaDescription:
      "Stay in Sangla, drive to Chitkul (India's last village), fish the Baspa, walk the Rakcham meadows. 5–6 day Kinnaur valley packages.",
    metaKeywords:
      "sangla valley, chitkul tour, baspa river, sangla kinnaur, rakcham village",
  },
  {
    slug: "dalhousie",
    name: "Dalhousie",
    tagline: "Five hills, Scottish skies, Khajjiar meadow",
    description:
      "Founded by the British in 1854 and spread across five wooded hills (Kathlog, Patreyn, Tehra, Bakrota, Bhangora), Dalhousie is the gentlest hill station in Himachal — colonial bungalows, churches half-hidden in deodar, and three short walks (Garam Sadak, Thandi Sadak, Subhash Baoli) that connect them. 22 km uphill sits Khajjiar — a circular Alpine meadow ringed by pines that locals call 'India's Mini Switzerland'.",
    bestTime: "March to June, September to October",
    altitude: "6,460 ft (1,970 m)",
    vibe: "Heritage, Family, Honeymoon",
    image: POOL.alpineMeadow,
    highlights: [
      "Khajjiar — 'Mini Switzerland of India' (22 km)",
      "St John's Church, St Patrick's & St Francis colonial churches",
      "Panchpula viewpoint & memorial",
      "Garam Sadak & Thandi Sadak walking circuits",
      "Kalatop Wildlife Sanctuary nature trail",
      "Day trip to Chamba town & Bhuri Singh Museum",
    ],
    categories: ["family", "honeymoon"],
    isActive: true,
    sortOrder: 10,
    metaTitle: "Dalhousie & Khajjiar Tour Packages | Mini Switzerland | Himvigo",
    metaDescription:
      "Plan a Dalhousie + Khajjiar break — colonial walks, Mini-Switzerland meadow, Kalatop forest. Easy family itineraries from Pathankot.",
    metaKeywords:
      "dalhousie tour packages, khajjiar tour, dalhousie khajjiar package, mini switzerland india",
  },
  {
    slug: "pathankot",
    name: "Pathankot",
    tagline: "The gateway to Himachal & J&K",
    description:
      "Strictly speaking a Punjab town — but practically, Pathankot is the rail and road junction every traveller heading to Dalhousie, Dharamshala, Chamba or Jammu passes through. Overnight Vande Bharat / Jhelum / Shaan-e-Punjab trains from Delhi & Mumbai land here; from the station it's a 3-hour drive to McLeod Ganj or Dalhousie. We run pickup-and-onward cabs from Pathankot 24×7.",
    bestTime: "Year-round (transit hub)",
    altitude: "1,036 ft (316 m)",
    vibe: "Transit, Gateway",
    image: POOL.trainJourney,
    highlights: [
      "Pathankot Junction — direct overnight trains from Delhi/Mumbai",
      "3-hour onward drive to McLeod Ganj/Dharamshala",
      "3-hour onward drive to Dalhousie",
      "4-hour onward drive to Chamba",
      "24×7 pickup cabs (sedan, SUV, Tempo Traveller)",
    ],
    categories: ["family"],
    isActive: true,
    sortOrder: 11,
    metaTitle: "Pathankot to Dharamshala / Dalhousie Cabs | Himvigo",
    metaDescription:
      "Reliable Pathankot pickup cabs to Dharamshala, McLeod Ganj, Dalhousie & Chamba. Verified drivers, transparent pricing.",
    metaKeywords:
      "pathankot to dharamshala, pathankot to dalhousie cab, pathankot taxi, pathankot mcleodganj",
  },
  {
    slug: "amritsar",
    name: "Amritsar",
    tagline: "Golden Temple & gateway to upper Himachal",
    description:
      "Punjab's spiritual capital — the Harmandir Sahib (Golden Temple), Jallianwala Bagh memorial, and the daily Wagah Border ceremony. For travellers heading to Dalhousie or Dharamshala, Amritsar's airport and train station are a popular alternative to Pathankot. From Amritsar it's ~5 hours by road to Dalhousie and ~6 hours to McLeod Ganj.",
    bestTime: "October to March",
    altitude: "768 ft (234 m)",
    vibe: "Pilgrimage, Gateway, Food",
    image: POOL.ridgeWalk,
    highlights: [
      "Harmandir Sahib (Golden Temple) & Langar",
      "Jallianwala Bagh memorial",
      "Wagah Border beating-retreat ceremony",
      "Old-city food walk (Kesar Da Dhaba, Bharawan Da)",
      "5 hr road to Dalhousie / 6 hr to McLeod Ganj",
    ],
    categories: ["spiritual", "family"],
    isActive: true,
    sortOrder: 12,
    metaTitle: "Amritsar to Dharamshala / Dalhousie Cabs | Himvigo",
    metaDescription:
      "Amritsar pickup cabs to Dalhousie & Dharamshala plus combined Golden-Temple + hills packages. Premium fleet, verified mountain drivers.",
    metaKeywords:
      "amritsar to dharamshala, amritsar to dalhousie, amritsar cab, golden temple package",
  },
  {
    slug: "leh-ladakh",
    name: "Leh - Ladakh",
    tagline: "Above the clouds, beyond the passes",
    description:
      "Ladakh is a Union Territory now, but for road-trippers it sits at the end of the legendary Manali-Leh highway — 473 km across five passes including Tanglang La (17,480 ft) and Baralacha La (16,040 ft). We package Ladakh as a Himachal-Ladakh combo: 2 days acclimatising in Manali, then the Sarchu camp, then Leh, with onward day-trips to Pangong Tso, Nubra Valley and Tso Moriri.",
    bestTime: "June to September (Manali-Leh road open)",
    altitude: "11,562 ft (3,524 m) — Leh",
    vibe: "Adventure, Offbeat, Bucket-list",
    image: POOL.highMountainRoad,
    highlights: [
      "Manali-Leh highway — 5 passes, 473 km",
      "Pangong Tso (3 Idiots lake) — 14,270 ft",
      "Nubra Valley & Hunder sand dunes",
      "Tso Moriri & Tso Kar lakes",
      "Hemis & Thiksey monasteries",
      "Khardung La (17,582 ft) — among world's highest motorable passes",
    ],
    categories: ["adventure", "offbeat"],
    isActive: true,
    sortOrder: 13,
    metaTitle: "Manali Leh Ladakh Road Trip Packages | Pangong & Nubra | Himvigo",
    metaDescription:
      "Drive the Manali-Leh highway with us — Sarchu camp, Pangong Tso, Nubra Valley, Khardung La. 9–12 day acclimatised itineraries with experienced mountain drivers.",
    metaKeywords:
      "leh ladakh package, manali leh road trip, pangong tso package, nubra valley, khardung la",
  },
];

// ─── Region-anchored packages ──────────────────────────────────────────
// (in addition to whatever's restored from backup)

export const PACKAGES = [
  // ── MANALI ──────────────────────────────────────────────────────────
  {
    slug: "manali-honeymoon-special",
    title: "Manali Honeymoon Special — 5 Days, 4 Nights",
    location: "Manali",
    pricePerPerson: 17999,
    durationDays: 5,
    durationNights: 4,
    imageUrls: [POOL.beasValley, POOL.snowSki, POOL.himalayaSunset],
    vehicleType: "Sedan",
    maxOccupancy: 2,
    description:
      "A premium honeymoon escape in the Beas valley — riverside boutique stay, a candlelit dinner at altitude, Solang adventure day and a private Atal Tunnel drop into Lahaul.",
    itinerary: [
      { day: 1, title: "Arrival — Old Manali", activities: "Bhuntar/Manali pickup, riverside check-in, welcome drinks, Mall Road evening." },
      { day: 2, title: "Solang Valley", activities: "Ropeway, paragliding (seasonal), ATV, snow point in winter." },
      { day: 3, title: "Atal Tunnel & Sissu", activities: "Cross into Lahaul, picnic at Sissu waterfall, return via Old Manali cafés." },
      { day: 4, title: "Naggar & Manikaran", activities: "Naggar Castle, Roerich art gallery, hot springs at Manikaran." },
      { day: 5, title: "Departure", activities: "Hadimba temple, drop to Bhuntar / Manali bus stand." },
    ],
    inclusions: [
      "Private sedan for 5 days",
      "4 nights premium riverside resort (twin sharing)",
      "Daily breakfast + 1 candlelit dinner",
      "Solang Valley sightseeing & ropeway",
      "Atal Tunnel & Sissu day trip",
      "All toll, parking & driver allowance",
    ],
    exclusions: ["Adventure activity tickets", "Lunches", "Personal expenses"],
    categories: ["honeymoon"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Manali Honeymoon Package | 5D/4N Solang & Atal Tunnel | Himvigo",
    metaDescription: "Premium 5-day Manali honeymoon — riverside stay, Solang day, Atal Tunnel drive, candlelit dinner. Built for couples.",
    metaKeywords: "manali honeymoon package, manali couple tour, solang valley, atal tunnel honeymoon",
  },
  {
    slug: "manali-family-special",
    title: "Manali Family Holiday — 6 Days, 5 Nights",
    location: "Manali",
    pricePerPerson: 14999,
    durationDays: 6,
    durationNights: 5,
    imageUrls: [POOL.beasValley, POOL.snowSki, POOL.travelVan],
    vehicleType: "Toyota Innova / Tempo Traveller",
    maxOccupancy: 7,
    description:
      "Built for groups travelling with parents and kids — sedan-and-tempo combo, no high-altitude detours, Solang activities, Naggar art, Manikaran pilgrimage and an easy Rohtang/Atal Tunnel day.",
    itinerary: [
      { day: 1, title: "Chandigarh → Manali", activities: "Pickup, scenic drive via Mandi, check-in." },
      { day: 2, title: "Solang Valley", activities: "Ropeway, snow point (winter), photo stops at Anjani Mahadev." },
      { day: 3, title: "Manali local", activities: "Hadimba temple, Vashisht hot springs, Old Manali walk." },
      { day: 4, title: "Atal Tunnel & Sissu", activities: "Cross into Lahaul, Sissu waterfall picnic." },
      { day: 5, title: "Naggar & Manikaran", activities: "Naggar Castle, Manikaran gurudwara." },
      { day: 6, title: "Manali → Chandigarh", activities: "Return drive, drop." },
    ],
    inclusions: [
      "Innova / Tempo for the full circuit",
      "5 nights 3-star family hotel (twin sharing)",
      "Daily breakfast + 4 dinners",
      "Driver allowance, toll, parking",
    ],
    exclusions: ["Activity tickets", "Snow gear rental", "Lunches"],
    categories: ["family"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Manali Family Tour Package | 6D/5N from Chandigarh | Himvigo",
    metaDescription: "6-day family Manali itinerary from Chandigarh — Solang, Atal Tunnel, Naggar, Manikaran. Innova / Tempo Traveller fleet.",
    metaKeywords: "manali family package, manali tour from chandigarh, manali innova package",
  },

  // ── SHIMLA ──────────────────────────────────────────────────────────
  {
    slug: "shimla-heritage-weekend",
    title: "Shimla Heritage Weekend — 3 Days, 2 Nights",
    location: "Shimla",
    pricePerPerson: 7999,
    durationDays: 3,
    durationNights: 2,
    imageUrls: [POOL.colonialHills, POOL.shimlaWinter, POOL.mistyForest],
    vehicleType: "Sedan",
    maxOccupancy: 4,
    description:
      "Two slow days on The Ridge with a heritage walk, the Kalka–Shimla toy train segment, Kufri snow point and Jakhu temple's giant Hanuman.",
    itinerary: [
      { day: 1, title: "Chandigarh → Shimla", activities: "Drive up via Solan, check-in, Mall Road evening, Ridge sunset." },
      { day: 2, title: "Kufri & Jakhu", activities: "Kufri snow point + Mahasu peak, Jakhu temple, heritage walk." },
      { day: 3, title: "Toy Train & Departure", activities: "Shimla → Kandaghat toy train segment (seasonal), drive back to Chandigarh." },
    ],
    inclusions: ["Sedan transfers", "2 nights 3-star stay", "Daily breakfast", "Toy train ticket (one segment)"],
    exclusions: ["Kufri pony / yak rides", "Lunches & dinners"],
    categories: ["family", "honeymoon"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Shimla Heritage Weekend Package | 3D/2N | Himvigo",
    metaDescription: "Long weekend in Shimla — Mall Road, Kufri snow point, toy train ride, Jakhu temple. Sedan transfers from Chandigarh.",
    metaKeywords: "shimla weekend package, shimla kufri tour, shimla 3 days package",
  },
  {
    slug: "shimla-manali-classic",
    title: "Shimla–Manali Classic — 7 Days, 6 Nights",
    location: "Shimla & Manali",
    pricePerPerson: 19999,
    durationDays: 7,
    durationNights: 6,
    imageUrls: [POOL.colonialHills, POOL.beasValley, POOL.snowSki],
    vehicleType: "Sedan / Innova",
    maxOccupancy: 4,
    description:
      "The classic North India itinerary — start in colonial Shimla, drive across Mandi to snowy Manali, do Solang and Atal Tunnel, end in Chandigarh.",
    itinerary: [
      { day: 1, title: "Chandigarh → Shimla", activities: "Drive up, Mall Road evening." },
      { day: 2, title: "Shimla local", activities: "Kufri, Jakhu temple, Christ Church, heritage walk." },
      { day: 3, title: "Shimla → Manali", activities: "Scenic drive via Mandi, evening at Mall Road Manali." },
      { day: 4, title: "Solang Valley", activities: "Ropeway, paragliding (seasonal), Anjani Mahadev." },
      { day: 5, title: "Atal Tunnel & Sissu", activities: "Cross into Lahaul, picnic in Sissu meadow." },
      { day: 6, title: "Manali local", activities: "Hadimba, Vashisht, Old Manali cafés, Naggar Castle." },
      { day: 7, title: "Manali → Chandigarh", activities: "Drop." },
    ],
    inclusions: ["Sedan/Innova transfers", "6 nights 3-star stay", "Daily breakfast + 3 dinners", "All toll & permits"],
    exclusions: ["Activity tickets", "Lunches"],
    categories: ["family", "honeymoon"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Shimla Manali Tour Package | 7D/6N Classic | Himvigo",
    metaDescription: "The classic Shimla + Manali itinerary — 7 days from Chandigarh, Solang day, Atal Tunnel drive. Built for families & couples.",
    metaKeywords: "shimla manali package, shimla manali tour, north india tour package",
  },

  // ── SPITI ───────────────────────────────────────────────────────────
  {
    slug: "spiti-circuit-9-days",
    title: "Spiti Valley Circuit — 9 Days, 8 Nights",
    location: "Spiti Valley",
    pricePerPerson: 26999,
    durationDays: 9,
    durationNights: 8,
    imageUrls: [POOL.coldDesert, POOL.monasteryTibet, POOL.highMountainRoad],
    vehicleType: "Tempo Traveller",
    maxOccupancy: 12,
    description:
      "The full Shimla → Spiti → Manali traverse — Kalpa apple orchards, Tabo's 1000-year-old gompa, Kaza acclimatisation, Hikkim post office, Key monastery sunrise and Chandratal Lake camping.",
    itinerary: [
      { day: 1, title: "Shimla → Sarahan", activities: "Drive into Kinnaur via Kufri, Hatu Peak detour." },
      { day: 2, title: "Sarahan → Kalpa", activities: "Sutlej road, sunset Kinnaur-Kailash view." },
      { day: 3, title: "Kalpa → Tabo", activities: "Cross Sumdo, evening at Tabo's mud-brick gompa." },
      { day: 4, title: "Tabo → Kaza", activities: "Dhankar Gompa & lake, Pin Valley viewpoints." },
      { day: 5, title: "Kaza local", activities: "Key Monastery, Kibber, Hikkim, Komic — high villages." },
      { day: 6, title: "Acclimatise — Langza & Demul", activities: "Fossil village walk, homestay night." },
      { day: 7, title: "Kaza → Chandratal", activities: "Cross Kunzum La, camp under Chandratal stars." },
      { day: 8, title: "Chandratal → Manali", activities: "Atal Tunnel drop, evening in Manali." },
      { day: 9, title: "Manali → Chandigarh", activities: "Drop." },
    ],
    inclusions: [
      "Tempo Traveller from Shimla → Manali → Chandigarh",
      "8 nights stay (homestay + hotel mix)",
      "All breakfasts & dinners",
      "Mountain driver experienced in Spiti",
      "Inner-line permits where required",
      "Chandratal camp (twin tent, sleeping bag)",
    ],
    exclusions: ["Travel to Shimla", "Lunches", "Monument entries"],
    categories: ["adventure", "offbeat"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Spiti Valley Package | 9D/8N Shimla-Spiti-Manali Loop | Himvigo",
    metaDescription: "Complete Spiti circuit — Kalpa, Tabo, Kaza, Key monastery, Hikkim post office, Chandratal Lake. 9-day tempo expedition.",
    metaKeywords: "spiti package, shimla spiti manali, spiti circuit, kaza tour, chandratal package",
  },
  {
    slug: "spiti-winter-experience",
    title: "Winter Spiti — Snow Leopard Country (7 Days)",
    location: "Spiti Valley",
    pricePerPerson: 32999,
    durationDays: 7,
    durationNights: 6,
    imageUrls: [POOL.coldDesert, POOL.monasteryTibet, POOL.snowyPeaks],
    vehicleType: "SUV (4×4)",
    maxOccupancy: 5,
    description:
      "December–March only: Spiti under snow, frozen Spiti river, monastery interiors with butter lamps, and (with luck) snow leopards in Kibber. Smaller groups, heated homestays.",
    itinerary: [
      { day: 1, title: "Shimla → Reckong Peo", activities: "Drive in via Kufri." },
      { day: 2, title: "Reckong Peo → Tabo", activities: "Slow descent into the cold desert." },
      { day: 3, title: "Tabo → Kaza", activities: "Dhankar viewpoint, monastery." },
      { day: 4, title: "Kibber — snow leopard tracking day", activities: "With wildlife guide." },
      { day: 5, title: "Key Monastery & Langza", activities: "Frozen waterfalls, fossil walks." },
      { day: 6, title: "Kaza → Reckong Peo", activities: "Return drive." },
      { day: 7, title: "Reckong Peo → Shimla", activities: "Drop." },
    ],
    inclusions: [
      "4×4 SUV with heater",
      "6 nights heated homestays",
      "All meals (high-altitude winter food plan)",
      "Wildlife guide for 1 day",
    ],
    exclusions: ["Travel to Shimla", "Personal cold-weather gear"],
    categories: ["adventure", "offbeat"],
    isFeatured: false,
    isActive: true,
    isTrek: false,
    metaTitle: "Winter Spiti Package | Snow Leopard Tour | Himvigo",
    metaDescription: "December-March only — Spiti in snow with optional snow leopard tracking in Kibber. 7-day small-group SUV tour.",
    metaKeywords: "winter spiti, snow leopard spiti, spiti december, spiti january",
  },

  // ── KASOL / PARVATI VALLEY ──────────────────────────────────────────
  {
    slug: "kasol-tosh-weekend",
    title: "Kasol + Tosh Backpacker Weekend — 4 Days, 3 Nights",
    location: "Kasol",
    pricePerPerson: 5999,
    durationDays: 4,
    durationNights: 3,
    imageUrls: [POOL.pineValley, POOL.riverValley, POOL.mistyForest],
    vehicleType: "Volvo + Tempo",
    maxOccupancy: 14,
    description:
      "Cheap, cheerful, perfect for first-time backpackers — overnight Volvo to Bhuntar, Kasol cafés, Tosh village stay and Manikaran hot springs.",
    itinerary: [
      { day: 1, title: "Delhi → Kasol", activities: "Overnight Volvo to Bhuntar, transfer to Kasol." },
      { day: 2, title: "Kasol & Manikaran", activities: "Riverside cafés, Manikaran gurudwara, hot springs." },
      { day: 3, title: "Tosh village", activities: "Drive to Tosh, hilltop café crawl, overnight stay." },
      { day: 4, title: "Tosh → Delhi", activities: "Trek down, drive to Bhuntar, overnight Volvo back." },
    ],
    inclusions: ["Delhi-Bhuntar return Volvo", "3 nights hostel/guesthouse (twin)", "Breakfasts", "Bhuntar-Kasol transfer"],
    exclusions: ["Lunches & dinners", "Personal expenses"],
    categories: ["adventure", "offbeat"],
    isFeatured: false,
    isActive: true,
    isTrek: false,
    metaTitle: "Kasol Tosh Weekend Package | Volvo + Stay | Himvigo",
    metaDescription: "Backpacker-budget 4-day Kasol + Tosh + Manikaran trip from Delhi. Overnight Volvo, hostel stays, café crawl.",
    metaKeywords: "kasol package from delhi, tosh weekend, kasol manikaran tour",
  },

  // ── DHARAMSHALA ─────────────────────────────────────────────────────
  {
    slug: "dharamshala-mcleodganj-3-days",
    title: "Dharamshala McLeod Ganj — 3 Days, 2 Nights",
    location: "Dharamshala",
    pricePerPerson: 8499,
    durationDays: 3,
    durationNights: 2,
    imageUrls: [POOL.triundMeadow, POOL.ridgeWalk, POOL.riverValley],
    vehicleType: "SUV",
    maxOccupancy: 6,
    description:
      "A long weekend with the Dalai Lama's temple, Norbulingka institute, Bhagsu waterfall, Dharamshala cricket stadium and an option to extend with a Triund overnight.",
    itinerary: [
      { day: 1, title: "Pickup & McLeod Ganj", activities: "From Pathankot/Dharamshala airport, check-in, Tsuglagkhang complex, café crawl." },
      { day: 2, title: "Norbulingka & Bhagsu", activities: "Tibetan crafts at Norbulingka, Bhagsu waterfall, cricket stadium." },
      { day: 3, title: "Departure", activities: "St John in the Wilderness, Dal Lake Naddi, drop." },
    ],
    inclusions: ["SUV transfers", "2 nights stay (boutique)", "Daily breakfast", "Pathankot/airport pickup"],
    exclusions: ["Lunches & dinners", "Triund trek (add-on)"],
    categories: ["spiritual", "family"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Dharamshala McLeod Ganj Package | 3D/2N | Himvigo",
    metaDescription: "Long-weekend Dharamshala + McLeod Ganj trip — Dalai Lama temple, Norbulingka, Bhagsu, optional Triund add-on.",
    metaKeywords: "dharamshala mcleodganj package, dharamshala 3 days, dharamshala from pathankot",
  },
  {
    slug: "bir-billing-paragliding-weekend",
    title: "Bir Billing Paragliding Weekend — 3 Days",
    location: "Bir Billing",
    pricePerPerson: 7499,
    durationDays: 3,
    durationNights: 2,
    imageUrls: [POOL.panoramicRidge, POOL.cloudPeaks, POOL.campfire],
    vehicleType: "SUV",
    maxOccupancy: 6,
    description:
      "Tandem paragliding from Billing (8,000 ft) to Bir (4,500 ft) — the world's second-highest paragliding site. Includes a Tibetan colony walk and Sherabling monastery visit.",
    itinerary: [
      { day: 1, title: "Pickup → Bir", activities: "Drive to Bir, billing colony walk, pre-flight briefing." },
      { day: 2, title: "Paragliding day", activities: "Drive to Billing take-off, tandem flight back to Bir, certificate." },
      { day: 3, title: "Sherabling & departure", activities: "Sherabling monastery, drop to Pathankot or Dharamshala." },
    ],
    inclusions: ["SUV transfers", "2 nights stay", "Tandem paragliding (1 flight, ~25 min)", "Pilot, helmet, GoPro footage"],
    exclusions: ["Weather rescheduling charges", "Lunches & dinners"],
    categories: ["adventure"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Bir Billing Paragliding Package | Himvigo",
    metaDescription: "Tandem paragliding from Billing to Bir + Sherabling monastery + Tibetan colony. 3-day weekend package.",
    metaKeywords: "bir billing paragliding, paragliding package himachal, bir tour package",
  },

  // ── KINNAUR / SANGLA / CHITKUL ──────────────────────────────────────
  {
    slug: "kinnaur-sangla-chitkul-6-days",
    title: "Kinnaur — Kalpa, Sangla & Chitkul — 6 Days, 5 Nights",
    location: "Kinnaur",
    pricePerPerson: 16999,
    durationDays: 6,
    durationNights: 5,
    imageUrls: [POOL.kinnerRange, POOL.riverValley, POOL.duskMountains],
    vehicleType: "SUV",
    maxOccupancy: 6,
    description:
      "The Old Hindustan-Tibet Road from Shimla to Chitkul — apple orchards in Kalpa, the Baspa valley in Sangla, and India's last village before Tibet.",
    itinerary: [
      { day: 1, title: "Shimla → Sarahan", activities: "Drive in, Bhimakali temple, overnight Sarahan." },
      { day: 2, title: "Sarahan → Kalpa", activities: "Sutlej road, sunset over Kinnaur-Kailash." },
      { day: 3, title: "Kalpa local", activities: "Reckong Peo, Roghi village, Suicide Point cliff." },
      { day: 4, title: "Kalpa → Sangla", activities: "Move to Sangla valley, Kamru fort." },
      { day: 5, title: "Chitkul day trip", activities: "Drive 22 km to last Indian village, Rakcham on return." },
      { day: 6, title: "Sangla → Shimla", activities: "Long drive back, drop." },
    ],
    inclusions: ["SUV from Shimla → Shimla", "5 nights stay (homestay + hotel mix)", "Breakfasts + 2 dinners", "Permits where applicable"],
    exclusions: ["Travel to Shimla", "Lunches"],
    categories: ["offbeat", "adventure"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Kinnaur Tour Package | Kalpa Sangla Chitkul 6 Days | Himvigo",
    metaDescription: "Drive the Old Hindustan-Tibet Road — Kalpa, Sangla, Chitkul. 6-day Kinnaur valley itinerary from Shimla.",
    metaKeywords: "kinnaur package, kalpa sangla chitkul tour, kinnaur kailash, sangla valley package",
  },

  // ── DALHOUSIE / KHAJJIAR ────────────────────────────────────────────
  {
    slug: "dalhousie-khajjiar-4-days",
    title: "Dalhousie + Khajjiar 'Mini Switzerland' — 4 Days, 3 Nights",
    location: "Dalhousie",
    pricePerPerson: 11999,
    durationDays: 4,
    durationNights: 3,
    imageUrls: [POOL.alpineMeadow, POOL.mistyForest, POOL.shimlaWinter],
    vehicleType: "Sedan / Innova",
    maxOccupancy: 4,
    description:
      "Colonial Dalhousie, the Khajjiar meadow ('India's Mini Switzerland'), Kalatop forest walk and an optional Chamba town day-trip.",
    itinerary: [
      { day: 1, title: "Pathankot → Dalhousie", activities: "Pickup, drive up, Subhash Baoli, Mall Road evening." },
      { day: 2, title: "Khajjiar & Kalatop", activities: "Mini Switzerland meadow, Kalatop sanctuary nature trail." },
      { day: 3, title: "Chamba day-trip", activities: "Chamba town, Bhuri Singh museum, Chaugan." },
      { day: 4, title: "Departure", activities: "Panchpula, drop at Pathankot station/airport." },
    ],
    inclusions: ["Sedan/Innova transfers", "3 nights 3-star stay", "Breakfasts", "Pathankot pickup & drop"],
    exclusions: ["Lunches & dinners", "Entry tickets"],
    categories: ["family", "honeymoon"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Dalhousie Khajjiar Tour Package | 4D/3N | Himvigo",
    metaDescription: "Plan Dalhousie + Khajjiar + Chamba — 4-day package from Pathankot. Colonial walks, Mini-Switzerland meadow, Kalatop forest.",
    metaKeywords: "dalhousie khajjiar package, dalhousie tour from pathankot, dalhousie 4 days",
  },

  // ── LEH-LADAKH (Manali-Leh) ─────────────────────────────────────────
  {
    slug: "manali-leh-ladakh-9-days",
    title: "Manali to Leh Ladakh Road Trip — 9 Days, 8 Nights",
    location: "Leh - Ladakh",
    pricePerPerson: 38999,
    durationDays: 9,
    durationNights: 8,
    imageUrls: [POOL.highMountainRoad, POOL.himalayaRange, POOL.campTent],
    vehicleType: "SUV / Innova",
    maxOccupancy: 5,
    description:
      "The full Manali–Leh highway with proper acclimatisation, Pangong Tso, Nubra Valley, Khardung La, Tso Moriri and a fly-out from Leh.",
    itinerary: [
      { day: 1, title: "Manali", activities: "Acclimatisation day, low-altitude walks." },
      { day: 2, title: "Manali → Sarchu", activities: "Cross Baralacha La, camp at 14,000 ft Sarchu." },
      { day: 3, title: "Sarchu → Leh", activities: "Cross Tanglang La (17,480 ft), arrive Leh." },
      { day: 4, title: "Leh local + rest", activities: "Shanti Stupa, Leh palace, Hall of Fame." },
      { day: 5, title: "Leh → Nubra (via Khardung La)", activities: "World's highest motorable pass, Hunder dunes." },
      { day: 6, title: "Nubra → Pangong Tso", activities: "Via Shyok river route, lakeside camp." },
      { day: 7, title: "Pangong → Leh", activities: "Return via Chang La pass." },
      { day: 8, title: "Tso Moriri day trip", activities: "Optional, full-day return." },
      { day: 9, title: "Fly out from Leh", activities: "Drop at IXL airport." },
    ],
    inclusions: [
      "Manali-Leh SUV with experienced highway driver",
      "8 nights stay (camp + hotel mix)",
      "All breakfasts + 6 dinners",
      "Inner-line permits for Nubra & Pangong",
      "Oxygen cylinder on demand",
    ],
    exclusions: ["Return flight from Leh", "Lunches", "Tso Moriri permits if added"],
    categories: ["adventure", "offbeat"],
    isFeatured: true,
    isActive: true,
    isTrek: false,
    metaTitle: "Manali Leh Ladakh Road Trip Package | 9D/8N | Himvigo",
    metaDescription: "The full Manali-Leh highway — Sarchu, Pangong, Nubra, Khardung La. 9-day acclimatised SUV expedition.",
    metaKeywords: "manali leh ladakh package, leh ladakh road trip, pangong tso package, nubra valley tour",
  },
];
